[win32] [squashme] Change commit set missing dependencies
Target: c74f6191621fdb441f3666417803e9d4d98bca9c.

GCC complains:
```
../lib/libglobal-static.a(global_init.cc.o): In function `global_init_preload_erasure_code(CephContext const*)':
/mnt/linux_build/ceph/src/global/global_init.cc:610: undefined reference to `ceph::ErasureCodePluginRegistry::preload(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::ostream*)'
../lib/libglobal-static.a(global_init.cc.o): In function `ceph::ErasureCodePluginRegistry::instance()':
/mnt/linux_build/ceph/src/erasure-code/ErasureCodePlugin.h:59: undefined reference to `ceph::ErasureCodePluginRegistry::singleton'
collect2: error: ld returned 1 exit status
../lib/libmon.a(OSDMonitor.cc.o): In function `OSDMonitor::normalize_profile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&, bool, std::ostream*)':
/mnt/linux_build/ceph/src/mon/OSDMonitor.cc:7165: undefined reference to `ceph::ErasureCodePluginRegistry::factory(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&, std::shared_ptr<ceph::ErasureCodeInterface>*, std::ostream*)'
../lib/libmon.a(OSDMonitor.cc.o): In function `OSDMonitor::get_erasure_code(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<ceph::ErasureCodeInterface>*, std::ostream*) const':
/mnt/linux_build/ceph/src/mon/OSDMonitor.cc:7258: undefined reference to `ceph::ErasureCodePluginRegistry::factory(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&, std::shared_ptr<ceph::ErasureCodeInterface>*, std::ostream*)'
../lib/libmon.a(OSDMonitor.cc.o): In function `ceph::ErasureCodePluginRegistry::instance()':
/mnt/linux_build/ceph/src/erasure-code/ErasureCodePlugin.h:59: undefined reference to `ceph::ErasureCodePluginRegistry::singleton'
../lib/libglobal-static.a(global_init.cc.o): In function `global_init_preload_erasure_code(CephContext const*)':
/mnt/linux_build/ceph/src/global/global_init.cc:610: undefined reference to `ceph::ErasureCodePluginRegistry::preload(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::ostream*)'
collect2: error: ld returned 1 exit status
```

ifdef out the changes.

Signed-off-by: Alin Gabriel Serdean <aserdean@cloudbasesolutions.com>