[squashme] Revert "[win32] Drop unused imports, unavailable on Windows"
This reverts commit 6f257ba98ec8bef8b50ca8e4460dd4390565d6ef.

Although they seem ununsed GCC complains:
In file included from /mnt/linux_build/ceph/src/common/pick_address.cc:15:
/mnt/linux_build/ceph/src/common/pick_address.h:49:61: note: forward declaration of ‘struct ifaddrs’
   49 | int pick_addresses(CephContext *cct, unsigned flags, struct ifaddrs *ifa,

same applies to statvfs.h/statfs.h:
error: aggregate ‘KStore::statfs(store_statfs_t*, osd_alert_list_t*)::statfs buf’ has incomplete type and cannot be defined
 1086 |   struct statfs buf;
      |                 ^~~
/mnt/temp3/ceph/src/os/kstore/KStore.cc:1091:9: error: ‘::statfs’ has not been declared
 1091 |   if (::statfs(basedir.c_str(), &buf) < 0) {

There are checks for HAVE_SYS_VFS_H maybe we should enhance it.

For now just add a placeholder for the file in src/include/windows/sys/statvfs.h

Signed-off-by: Alin Gabriel Serdean <aserdean@cloudbasesolutions.com>